(function(){'use strict';const $=id=>document.getElementById(id),M=CSPImpact;let accessState=null,biasState=null,privacyState=null,authState=null,keyState=null,licenseState=null;
const text=(id,value)=>$(id).textContent=value;
function status(id,value,error=false){text(id,value);$(id).classList.toggle('error',error);}
function row(parent,values){const tr=document.createElement('tr');values.forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});parent.append(tr);}
function checked(parent){return [...$(parent).querySelectorAll('input:checked')].map(x=>x.value);}
function checks(parent,items,onchange,initial=[]){items.forEach(item=>{const label=document.createElement('label');label.className='intervention';const input=document.createElement('input');input.type='checkbox';input.value=item.id;input.checked=initial.includes(item.id);input.addEventListener('change',onchange);const span=document.createElement('span');span.textContent=item.name;if(item.cost!==undefined){const small=document.createElement('small');small.textContent=item.cost+' model budget '+(item.cost===1?'unit':'units');span.append(small);}label.append(input,span);$(parent).append(label);});}
function setChecked(parent,ids){$(parent).querySelectorAll('input').forEach(el=>el.checked=ids.includes(el.value));}
function access(){try{if(!$('a-budget').value.trim())throw Error('Enter a whole-number budget from 0 to 6.');accessState=M.access(checked('a-options'),Number($('a-budget').value));const s=accessState;text('a-eligible',s.eligible+' / 100');text('a-cost',s.cost+' / '+s.budget);text('a-gain','+'+(s.eligible-40));status('a-status',s.withinBudget?'Within budget. Under the model assumptions, '+s.eligible+' people meet every listed access requirement.':'This plan exceeds the budget by '+(s.cost-s.budget)+' '+(s.cost-s.budget===1?'unit':'units')+'. The chart shows its hypothetical access effect, not a feasible funded plan.',!s.withinBudget);$('a-table').replaceChildren();let svg='<text x="290" y="22" font-size="14">People · each bar uses the same scale</text>';s.groups.forEach((g,i)=>{row($('a-table'),[g.name,g.count,g.eligible?'No listed barrier remains':g.remaining.map(id=>({connection:'No reliable connection',device:'No suitable device',skills:'Skills support needed',accessibility:'Interface access barrier'})[id]).join(' + ')]);const y=45+i*44,w=g.count*8;svg+='<text x="278" y="'+(y+19)+'" text-anchor="end" font-size="14">'+g.name+'</text><rect x="290" y="'+y+'" width="'+w+'" height="28" fill="'+(g.eligible?'#28766f':'#e7ecef')+'" stroke="'+(g.eligible?'#28766f':'#879ca9')+'"'+(g.eligible?'':' stroke-dasharray="5 3"')+'/><text x="'+(300+w)+'" y="'+(y+19)+'" font-size="15">'+g.count+'</text>';});svg+='<text x="290" y="336" font-size="13">40 people have no listed barrier at baseline.</text>';$('a-chart').innerHTML=svg;}catch(e){accessState=null;status('a-status',e.message,true);['a-eligible','a-cost','a-gain'].forEach(id=>text(id,'—'));$('a-table').replaceChildren();$('a-chart').replaceChildren();}}
checks('a-options',M.INTERVENTIONS,access);$('a-budget').addEventListener('input',access);$('a-reset').onclick=()=>{setChecked('a-options',[]);$('a-budget').value='4';access();};$('a-both').onclick=()=>{setChecked('a-options',['connection','device']);access();};
function bias(){biasState=M.bias(Number($('b-north').value));const b=biasState;text('b-mix',b.north+' North people + '+b.south+' South people = 100 sampled people');text('b-raw',b.samplePercent+'%');text('b-weighted','44%');const gap=b.samplePercent-44;text('b-gap',(gap>0?'+':'')+gap+' pp');text('b-formula','Raw sample:\n('+b.north+' × 20% + '+b.south+' × 80%) / 100\n= ('+b.northNeed+' + '+b.southNeed+') / 100 = '+b.samplePercent+'%\n\nPopulation-weighted model:\n0.60 × 20% + 0.40 × 80% = 44%');$('b-table').replaceChildren();row($('b-table'),['North',b.north,'20%',b.northNeed]);row($('b-table'),['South',b.south,'80%',b.southNeed]);let svg='<text x="160" y="24" font-size="14">North (blue) + South (teal)</text>';[[b.north,b.south,'Sample'],[60,40,'Population']].forEach(([n,s,label],i)=>{const y=55+i*90,nw=n*4.8,sw=s*4.8;svg+='<text x="135" y="'+(y+27)+'" text-anchor="end" font-size="16">'+label+'</text><rect x="160" y="'+y+'" width="'+nw+'" height="42" fill="#225a83"/><rect x="'+(160+nw)+'" y="'+y+'" width="'+sw+'" height="42" fill="#28766f"/>';if(n>=10)svg+='<text x="'+(160+nw/2)+'" y="'+(y+27)+'" text-anchor="middle" fill="white" font-size="15">'+n+'%</text>';if(s>=10)svg+='<text x="'+(160+nw+sw/2)+'" y="'+(y+27)+'" text-anchor="middle" fill="white" font-size="15">'+s+'%</text>';});svg+='<text x="160" y="226" font-size="13">Within-area constructed rates stay fixed at 20% / 80%.</text>';$('b-chart').innerHTML=svg;}
$('b-north').oninput=bias;[['b-default',80],['b-population',60],['b-reverse',40]].forEach(([id,n])=>$(id).onclick=()=>{$('b-north').value=n;bias();});
function privacy(){privacyState=M.privacy(checked('s-fields'),$('s-release').value);const p=privacyState;text('s-collect',M.FIELDS.filter(f=>p.selected.includes(f.id)).map(f=>f.name).join('; ')||'No fields selected');text('s-process',p.purposeSupported?'Combine reports by zone and calculate proportions.':'Required fields are missing for the stated zone comparison.');text('s-publish',!p.purposeSupported?'Review the intended release after resolving missing data.':p.release==='aggregate'?'Zone-level totals and proportions.':'Individual report records.');status('s-status',!p.purposeSupported?'The stated comparison is missing: '+p.missing.join(', ')+'.':p.extra.length?'The stated purpose is supported, but '+p.extra.length+' extra field(s) need a separate justification.':'Both required fields are selected; no extra listed field is collected.',!p.purposeSupported);$('s-risks').replaceChildren();p.risks.forEach(r=>{const li=document.createElement('li');li.textContent=r;$('s-risks').append(li);});}
checks('s-fields',M.FIELDS,privacy,['zone','shadeRating','exactGPS','email','name']);$('s-release').onchange=privacy;$('s-minimal').onclick=()=>{setChecked('s-fields',['zone','shadeRating']);privacy();};$('s-all').onclick=()=>{setChecked('s-fields',M.FIELDS.map(f=>f.id));privacy();};
function auth(){authState=M.authentication(checked('s-factors'));status('s-factor-result',authState.categories.length?(authState.multifactor?'Multiple factor categories: ':'Only one factor category: ')+authState.categories.join(' + ')+'.': 'Choose examples to compare factor categories.');}
checks('s-factors',M.FACTORS,auth);const keyNames={shared:'Shared secret key',blakePublic:'Blake’s public key',blakePrivate:'Blake’s private key',alexPublic:'Alex’s public key'};['s-encrypt','s-decrypt'].forEach(id=>Object.entries(keyNames).forEach(([value,name])=>{const option=document.createElement('option');option.value=value;option.textContent=name;$(id).append(option);}));
function keyReset(){keyState=null;status('s-key-result','Choices changed · check the encryption and decryption roles.');}['s-key-mode','s-encrypt','s-decrypt'].forEach(id=>$(id).onchange=keyReset);$('s-check-keys').onclick=()=>{keyState=M.keyRoles($('s-key-mode').value,$('s-encrypt').value,$('s-decrypt').value);const k=keyState;status('s-key-result',k.correct?'Both roles match this confidentiality model. '+($('s-key-mode').value==='public'?'Alex uses Blake’s public key; Blake keeps the matching private key secret.':'Alex and Blake use the shared secret key; it must be exchanged and kept securely.'):'Revise '+[!k.encryptionCorrect?'the encryption key':'',!k.decryptionCorrect?'the decryption key':''].filter(Boolean).join(' and ')+'. For this model, encrypt with '+keyNames[k.expectedEncryption]+' and decrypt with '+keyNames[k.expectedDecryption]+'.',!k.correct);};
M.ASSETS.forEach(a=>{const option=document.createElement('option');option.value=a.id;option.textContent=a.label;$('r-asset').append(option);});
function resetLicense(){licenseState=null;status('r-status','Read the card, choose an action and explain your reasoning.');}
function asset(){const a=M.ASSETS.find(a=>a.id===$('r-asset').value);text('r-title',a.title);text('r-source','Creator: '+a.creator+' · '+a.source);text('r-terms',a.terms);$('r-credit').checked=false;$('r-changes').checked=false;resetLicense();}
$('r-asset').onchange=asset;['r-action','r-credit','r-changes'].forEach(id=>$(id).onchange=resetLicense);$('r-check').onclick=()=>{licenseState=M.licenseReview($('r-asset').value,$('r-action').value,$('r-credit').checked,$('r-changes').checked);status('r-status',licenseState.status+' · '+licenseState.explanation,!licenseState.ready&&$('r-action').value==='reuse');};
function route(){const key=['access','bias','security','responsibility'].includes(location.hash.slice(1))?location.hash.slice(1):'access';document.querySelectorAll('.tabs a').forEach(a=>{if(a.hash==='#'+key)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});['access','bias','security','responsibility'].forEach(name=>$('workspace-'+name).hidden=name!==key);}
$('v-save').onclick=()=>{const record={case:'Community Shade Map — constructed classroom model',workspace:location.hash||'#access',access:accessState,bias:biasState,privacy:privacyState,authentication:authState,keyChoice:{mode:$('s-key-mode').value,encryption:$('s-encrypt').value,decryption:$('s-decrypt').value,review:keyState},reuse:{asset:$('r-asset').value,action:$('r-action').value,credit:$('r-credit').checked,changes:$('r-changes').checked,reason:$('r-explanation').value,review:licenseState},notes:Object.fromEntries(['access','bias','security','responsibility','conclusion'].map(k=>[k,$('v-'+k).value]))};const url=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='AP_CSP_Chapter6_Investigation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};window.addEventListener('hashchange',route);access();bias();privacy();auth();asset();route();
})();
