/* Constructed classroom cases. No live population data or real security operations. */
(function(root){'use strict';
const INTERVENTIONS=[{id:'connection',name:'Connection support',cost:2},{id:'device',name:'Device loans',cost:2},{id:'skills',name:'Guided practice',cost:1},{id:'accessibility',name:'Accessible interface',cost:1}];
const GROUPS=[{name:'No listed barrier',count:40,barriers:[]},{name:'Connection only',count:20,barriers:['connection']},{name:'Device only',count:15,barriers:['device']},{name:'Skills only',count:10,barriers:['skills']},{name:'Interface access only',count:5,barriers:['accessibility']},{name:'Connection + device',count:10,barriers:['connection','device']}];
function access(selected=[],budget=4){if(!Array.isArray(selected)||selected.some(x=>!INTERVENTIONS.some(i=>i.id===x))||!Number.isInteger(budget)||budget<0||budget>6)throw Error('Use the listed interventions and a whole-number budget from 0 to 6.');const ids=new Set(selected),cost=INTERVENTIONS.filter(x=>ids.has(x.id)).reduce((s,x)=>s+x.cost,0),groups=GROUPS.map(g=>({...g,barriers:[...g.barriers],remaining:g.barriers.filter(b=>!ids.has(b))}));groups.forEach(g=>g.eligible=g.remaining.length===0);return {groups,cost,budget,withinBudget:cost<=budget,eligible:groups.reduce((s,g)=>s+(g.eligible?g.count:0),0),total:100};}
function bias(north=80){if(!Number.isInteger(north)||north<5||north>95||north%5)throw Error('Use North counts from 5 to 95 in steps of 5.');const south=100-north,northNeed=north/5,southNeed=south*4/5;return {north,south,northNeed,southNeed,samplePercent:northNeed+southNeed,populationWeightedPercent:44,populationNorth:60,populationSouth:40};}
const FIELDS=[{id:'zone',name:'North / South zone',required:true},{id:'shadeRating',name:'Need-more-shade response',required:true},{id:'exactGPS',name:'Exact location history',required:false},{id:'email',name:'Contributor email',required:false},{id:'name',name:'Contributor name',required:false}];
function privacy(selected=['zone','shadeRating'],release='aggregate'){if(!Array.isArray(selected)||selected.some(id=>!FIELDS.some(f=>f.id===id))||!['aggregate','raw'].includes(release))throw Error('Choose listed field names and a release format.');const ids=new Set(selected),missing=FIELDS.filter(f=>f.required&&!ids.has(f.id)).map(f=>f.name),extra=FIELDS.filter(f=>!f.required&&ids.has(f.id)).map(f=>f.name);return {selected:[...ids],release,missing,extra,purposeSupported:!missing.length,minimal:!missing.length&&!extra.length,risks:[...(extra.length?['Extra fields need a purpose, access controls and a retention decision.']:[]),release==='raw'?'Publishing individual records can expose sensitive details and support linkage.':'Aggregates reduce detail, but small groups or linkage may still reveal information.','Encryption does not decide who should collect or publish the data.']};}
const FACTORS=[{id:'password',name:'Password',category:'knowledge'},{id:'pin',name:'PIN',category:'knowledge'},{id:'phone',name:'One-time code from a possessed phone',category:'possession'},{id:'fingerprint',name:'Fingerprint',category:'inherence'}];
function authentication(selected=[]){if(!Array.isArray(selected)||selected.some(id=>!FACTORS.some(f=>f.id===id)))throw Error('Choose listed authentication examples.');const ids=new Set(selected),categories=[...new Set(FACTORS.filter(f=>ids.has(f.id)).map(f=>f.category))];return {categories,multifactor:categories.length>=2,selected:[...ids]};}
function keyRoles(mode,encryption,decryption){if(!['symmetric','public'].includes(mode))throw Error('Choose a key model.');const valid=['shared','blakePublic','blakePrivate','alexPublic'];if(!valid.includes(encryption)||!valid.includes(decryption))throw Error('Choose a listed key.');const expectedEncryption=mode==='symmetric'?'shared':'blakePublic',expectedDecryption=mode==='symmetric'?'shared':'blakePrivate';return {encryptionCorrect:encryption===expectedEncryption,decryptionCorrect:decryption===expectedDecryption,correct:encryption===expectedEncryption&&decryption===expectedDecryption,expectedEncryption,expectedDecryption};}
const ASSETS=[{id:'icon',title:'Shade-tree icon',creator:'Map Art Team',source:'Fictional classroom asset card A',terms:'Sharing and adapting for any purpose are allowed if you credit the creator and identify changes.',kind:'credit',label:'A · Reuse with conditions'},{id:'chart',title:'Research chart',creator:'Study Group',source:'Fictional classroom asset card B',terms:'You may read this chart. No permission to reproduce it is stated.',kind:'read',label:'B · Read permission only'},{id:'code',title:'Your team’s original code',creator:'Your project team',source:'Fictional classroom asset card C',terms:'In this case, your team created all this code itself for this project; it includes no third-party code.',kind:'original',label:'C · Original team work'},{id:'photo',title:'Photo found online',creator:'Not yet identified',source:'Fictional classroom asset card D',terms:'No creator permission or reuse license has been found.',kind:'unknown',label:'D · Unknown permissions'}];
function licenseReview(assetId,action,credit=false,changes=false){const asset=ASSETS.find(a=>a.id===assetId);if(!asset||!['reuse','ask','replace'].includes(action))throw Error('Choose an asset and an action.');if(action==='ask')return {ready:false,status:'Permission pending',explanation:'Request permission for the intended use and wait for the answer. Asking is not receiving permission.'};if(action==='replace')return {ready:true,status:'Choose an authorised replacement',explanation:'Do not use this asset. Create an original replacement or find one with suitable reuse terms and follow them.'};if(asset.kind==='original')return {ready:true,status:'Consistent with this case',explanation:'The case states that the team created this code. Document authorship and recheck any later third-party additions.'};if(asset.kind==='credit')return {ready:credit&&changes,status:credit&&changes?'Required conditions selected':'A stated condition is missing',explanation:credit&&changes?'You selected both conditions. Include the creator credit and changes statement with the reused work, and keep the card terms in the source record.':'Record creator credit and identify changes (or state unchanged). Attribution alone does not replace all permission conditions.'};return {ready:false,status:'Reuse permission not established',explanation:asset.kind==='read'?'Permission to read does not establish permission to reproduce. Obtain permission for the intended use or choose an authorised alternative.':'Online availability is not evidence of a reuse license. Find the source and terms, ask permission, or choose an authorised alternative.'};}
const api={INTERVENTIONS,GROUPS,access,bias,FIELDS,privacy,FACTORS,authentication,keyRoles,ASSETS,licenseReview};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.CSPImpact=api;
})(typeof window!=='undefined'?window:this);
