(function(){'use strict';
const bank=JSON.parse(document.getElementById('question-data').textContent),M=window.CSPReview.make(bank),KEY='apcsp-review-v1';const $=id=>document.getElementById(id),labels=['A','B','C','D'];let state=M.empty(),active=null;
function status(msg,error=false){$('quiz-status').textContent=msg;$('quiz-status').classList.toggle('error',error);}
try{const raw=localStorage.getItem(KEY);if(raw){state=M.normalize(JSON.parse(raw));for(const r of Object.values(state.sets))M.pause(r,Date.now());status('已恢复本机练习记录，计时处于暂停状态。');}}catch(e){status('未能读取已存记录，先显示空白练习；本页操作会保存新的练习记录。',true);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){status('当前浏览器无法保存记录；离开前请导出复盘报告。',true);}}
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
function currentSet(){return bank.sets.find(s=>s.id===active);}
function clock(){if(!active)return;const r=state.sets[active],ms=M.remaining(r,Date.now()),secs=Math.ceil(ms/1000);$('clock').textContent=String(Math.floor(secs/60)).padStart(2,'0')+':'+String(secs%60).padStart(2,'0');$('start-clock').disabled=r.submitted||r.deadline!==null||ms===0;$('pause-clock').disabled=r.deadline===null;$('time-note').textContent=ms===0?'练习时间已到。你仍可完成或复盘；本工具不会自动交卷。':r.deadline!==null?'计时中；切换题组会暂停。':'计时暂停；可以先读练习说明。';if(ms===0&&r.deadline!==null){M.pause(r,Date.now());save();}}
function showResults(){const box=$('results');box.replaceChildren();const rec=state.sets[active];box.hidden=!rec.submitted;if(!rec.submitted)return;const result=M.grade(active,rec);box.append(el('h2',`Review / 复盘：${result.correct} / ${result.total}`));box.append(el('p','双选题须完整选对才计1题；没有部分分。这里仅统计本组原创练习的正确题数，不预测AP成绩。'));
 const chart=el('div',undefined,'topic-bars');for(const [topic,t] of Object.entries(result.byTopic)){const row=el('div',undefined,'topic-row');row.append(el('span',`${topic} · ${t.correct}/${t.total}`));const progress=el('progress');progress.max=t.total;progress.value=t.correct;progress.setAttribute('aria-label',`${topic}: ${t.correct} correct out of ${t.total}`);row.append(progress);chart.append(row);}box.append(chart);
 const wrong=result.rows.filter(x=>!x.correct);box.append(el('h3',wrong.length?'Review these questions / 从错题开始':'Revisit your reasoning / 检查推理过程'));
 const list=el('ul');for(const row of wrong){const q=bank.questions.find(q=>q.id===row.id),li=el('li'),a=el('a',`${row.id}: ${q.remediation.label}`);a.href=q.remediation.url;li.append(a,document.createTextNode(row.blank?' · 未作答':row.incomplete?' · 选择数量不足':' · 核对解析和原条件'));list.append(li);}box.append(list);box.append(el('p','复盘动作：写出错因 → 用自己的话解释条件或算法 → 先重做一道旧课题 → 隔天再试本组。', 'note'));
}
function render(){const set=currentSet(),rec=state.sets[active];$('set-title').textContent=set.title;$('set-info').textContent=`${set.questionIds.length} original questions · suggested ${set.minutes} minutes · 原创练习，非官方实考试卷`;const container=$('questions');container.replaceChildren();for(const id of set.questionIds){const q=bank.questions.find(q=>q.id===id),card=el('article',undefined,'question card');card.id=id;const field=el('fieldset'),legend=el('legend',id+' · '+q.topic+' · '+(q.answer.length===2?'Select TWO':'Select ONE'));field.append(legend,el('p',q.stem));if(q.code)field.append(el('pre',q.code));q.options.forEach((text,i)=>{const label=el('label',undefined,'option'),input=el('input');input.type=q.answer.length===1?'radio':'checkbox';input.name=id;input.value=String(i);input.id=id+'-'+i;input.checked=(rec.answers[id]||[]).includes(i);input.disabled=rec.submitted;input.addEventListener('change',()=>{if(!M.select(rec,id,i,input.checked)){input.checked=false;status('本题只能选择两个选项。请先取消一个选项。',true);return;}status('选择已记录。点击“完成并查看解析”后统一核对答案。');save();});label.append(input,el('span',labels[i]+'. '+text));field.append(label);});card.append(field);
 if(rec.submitted){const r=M.grade(active,rec).rows.find(r=>r.id===id),feedback=el('div',undefined,'feedback '+(r.correct?'correct':'incorrect'));feedback.append(el('strong',(r.correct?'Correct / 正确':'Revisit / 再检查')+' · Answer: '+q.answer.map(i=>labels[i]).join(', ')),el('p',q.rationale),el('p',q.explanation));const a=el('a','回到课程：'+q.remediation.label);a.href=q.remediation.url;feedback.append(a);card.append(feedback);}container.append(card);}
 $('finish').disabled=rec.submitted;$('restart-panel').hidden=true;showResults();clock();}
function tab(){const wanted=location.hash.slice(1);const next=bank.sets.some(s=>s.id===wanted)?wanted:bank.sets[0].id;if(active===next)return;if(active){M.pause(state.sets[active],Date.now());save();}active=next;for(const s of bank.sets){const a=$('tab-'+s.id);if(s.id===active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');}render();}
$('start-clock').addEventListener('click',()=>{M.start(state.sets[active],Date.now());save();clock();});$('pause-clock').addEventListener('click',()=>{M.pause(state.sets[active],Date.now());save();clock();});
$('finish').addEventListener('click',()=>{const r=state.sets[active];M.pause(r,Date.now());r.submitted=true;render();status('本组已结束。未作答或未完整选对的题不计正确；可查看逐题解析与补练入口。');save();$('results').scrollIntoView({behavior:'smooth',block:'start'});});
$('restart').addEventListener('click',()=>{$('restart-panel').hidden=false;});$('cancel-restart').addEventListener('click',()=>{$('restart-panel').hidden=true;});$('confirm-restart').addEventListener('click',()=>{state.sets[active]=M.freshSet(active);render();status('本组新一轮练习已开始，计时尚未启动。其他题组记录保留。');save();});
$('export-report').addEventListener('click',()=>{const lines=['AP CSP Chapter 8 | Original practice report','This report is not an official AP score.',''];for(const set of bank.sets){const r=state.sets[set.id];lines.push(set.title,r.submitted?'Completed':'In progress; answers not graded');if(r.submitted){const g=M.grade(set.id,r);lines.push(`Correct: ${g.correct}/${g.total}`);for(const row of g.rows){const q=bank.questions.find(q=>q.id===row.id);lines.push(`${q.id} ${row.topic}: ${row.correct?'correct':'revisit'} | selected ${row.selected.map(i=>labels[i]).join(', ')||'(blank)'} | answer ${q.answer.map(i=>labels[i]).join(', ')} | ${q.remediation.label}`);}}lines.push('');}const blob=new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='AP_CSP_Review_Report.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
window.addEventListener('hashchange',tab);window.addEventListener('pagehide',()=>{if(active){M.pause(state.sets[active],Date.now());save();}});tab();setInterval(clock,500);
})();
